### ISSUE TITLE
Tornado's log messages don't contain enologs.tool and enologs.serviceName

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker_async#14]
We shoud fill record.checker.name with a static variable instead of pulling from the record

**Comment by Trolldemorted** [comment]
I just found this bug again before I remembered I already opened it!

![grafik](https://user-images.githubusercontent.com/10261186/83075067-8b7b0580-a073-11ea-9034-104b25fc9ef1.png)

**Comment by mauricesvp** [comment]
How do you reproduce this btw? Will look into it later

**Comment by Trolldemorted** [comment]
This is already fixed :)

You need a checker that logs stuff outside the context of a checker task.
