### ISSUE TITLE
Sometimes the method field is missing

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker_async#15]
@Savallator can reproduce

**Comment by Savallator** [comment]
I already fixed it locally, just need the rights to branch/pr  for this repo and the enocore repo, since it needed to be added in both

**Comment by Savallator** [comment]
The non-async checker might have the same problem...

**Comment by Trolldemorted** [comment]
@enowars/engineering should have the required permissions now!

Please respect the semver rules when pushing new releases - adding a new property to a dataclass is an api breaking change.

**Comment by Trolldemorted** [comment]
in 0.3.*
