### ISSUE TITLE
CheckerResultMessage should contain the message if present

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker_async#27]

**Comment by ldruschk** [comment]
Currently there is no way to include a message at all, as this is missing from https://github.com/enowars/enochecker_core/blob/be361f0cce07dea6555d078f47f486491098ee58/enochecker_core/__init__.py#L81

We should either merge this with the exception classes from https://github.com/enowars/enochecker/blob/main/src/enochecker/results.py or remove them from enochecker_core altogether and create exceptions for use within enochecker_async only

**Comment by Trolldemorted** [comment]
Don't all exceptions have a message field?

**Comment by ldruschk** [comment]
Of course, my bad
