### ISSUE TITLE
don't start gets for failed puts

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker_async#7]

**Comment by ldruschk** [comment]
I believe this issue can be closed since this is now/should be handled by the Engine: https://github.com/enowars/EnoEngine/issues/105

**Comment by Trolldemorted** [comment]
We should have a look at the engine source for that, but imho checkers should be resilient, follow defensive programming, and return mumble in those cases.

**Comment by ldruschk** [comment]
With the new specification here https://github.com/enowars/specification this is no longer relevant for the library and can be closed, right?
